### ISSUE TITLE
Screenshot causes crash on Windows

### ISSUE THREAD

**Issue by Eiim** [agateau/pixelwheels#120]
When pressing "s" to take a screenshot on Windows, the game crashes with the following error:

```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error writing file: .local\share\pixelwheels\screenshot-2021-05-30-13:39:42.925.png (External)
        at com.badlogic.gdx.files.FileHandle.write(FileHandle.java:302)
        at com.badlogic.gdx.graphics.PixmapIO$PNG.write(PixmapIO.java:222)
        at com.agateau.utils.ScreenshotCreator.saveScreenshot(ScreenshotCreator.java:44)
        at com.agateau.pixelwheels.PwGame.render(PwGame.java:104)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at com.agateau.pixelwheels.desktop.DesktopLauncher.main(DesktopLauncher.java:37)
Caused by: java.io.FileNotFoundException: C:\Users\eiim\.local\share\pixelwheels\screenshot-2021-05-30-13:39:42.925.png (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at com.badlogic.gdx.files.FileHandle.write(FileHandle.java:298)
        ... 7 more
```

**Comment by agateau** [comment]
Oups, looks like the code does not check if the screenshot directory has been created (and the directory is not very Windows-friendly). Going to look into it. In the mean time it should work if you create the missing directories.

**Comment by Eiim** [comment]
The directory does exist, it stores the debug.xml, gameplay.xml, and gamestats.json files.

**Comment by Eiim** [comment]
Oh, I just realized that the problem is that files can't contain `:` on Windows.

**Comment by agateau** [comment]
Oh right! That's an easy fix then. Will look at it tomorrow.
