### ISSUE TITLE
GdxRuntimeException

### ISSUE THREAD

**Issue by SArsalanK** [agateau/pixelwheels#18]
com.badlogic.gdx.utils.GdxRuntimeException: Error reading file: ui/uiskin.atlas (Internal)
        at com.badlogic.gdx.backends.android.AndroidFileHandle.read(AndroidFileHandle.java:77)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:103)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216)
        at com.agateau.ui.StrictTextureAtlas.<init>(StrictTextureAtlas.java:36)
        at com.agateau.ui.UiAssets.<init>(UiAssets.java:36)
        at com.agateau.pixelwheels.Assets.<init>(Assets.java:57)
        at com.agateau.pixelwheels.PwGame.create(PwGame.java:88)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1555)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

**Comment by agateau** [comment]
Hi! Looks like you haven't built and packed the assets. Look at https://github.com/agateau/pixelwheels/blob/master/doc/building.md for details

**Comment by agateau** [comment]
No answer, closing.
